import type { ServerConfig } from '../types.js';

export interface PluginConfig {
  pluginDir: string;
  filename: string;
  content: string;
}

export function generatePluginConfigs(plugins: string[], config: ServerConfig): PluginConfig[] {
  const configs: PluginConfig[] = [];

  // EssentialsX config
  if (plugins.includes('essentialsx')) {
    configs.push({
      pluginDir: 'Essentials',
      filename: 'config.yml',
      content: generateEssentialsXConfig(config),
    });
  }

  // LuckPerms config
  if (plugins.includes('luckperms')) {
    configs.push({
      pluginDir: 'LuckPerms',
      filename: 'config.yml',
      content: generateLuckPermsConfig(config),
    });
  }

  // GriefPrevention config
  if (plugins.includes('griefprevention')) {
    configs.push({
      pluginDir: 'GriefPrevention',
      filename: 'config.yml',
      content: generateGriefPreventionConfig(config),
    });
  }

  // TAB config
  if (plugins.includes('tab-wasTaken') || plugins.includes('tab')) {
    configs.push({
      pluginDir: 'TAB',
      filename: 'config.yml',
      content: generateTABConfig(config),
    });
  }

  // CoreProtect config
  if (plugins.includes('coreprotect')) {
    configs.push({
      pluginDir: 'CoreProtect',
      filename: 'config.yml',
      content: generateCoreProtectConfig(config),
    });
  }

  // DiscordSRV config (basic template)
  if (plugins.includes('discordsrv')) {
    configs.push({
      pluginDir: 'DiscordSRV',
      filename: 'config.yml',
      content: generateDiscordSRVConfig(config),
    });
  }

  return configs;
}

function generateEssentialsXConfig(config: ServerConfig): string {
  return `# EssentialsX Configuration
# Generated by StartServer

############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# This is the EssentialsX config file.
# Server: ${config.serverName}
# Generated: ${new Date().toISOString()}

############################################################
# +------------------------------------------------------+ #
# |                 Essentials (Global)                  | #
# +------------------------------------------------------+ #
############################################################

# The motd and rules are now configured in the locale files.

# If you need the old format, you can change the locale to 'en'.

# Called when a player uses /op or /deop
notify-on-op: true

# Called when a player uses /god
notify-on-god: true

# Called when a player uses /togglejail
notify-on-jail: true

############################################################
# +------------------------------------------------------+ #
# |                      Kits                            | #
# +------------------------------------------------------+ #
############################################################

# Create custom kits here.
# The format is:
# kits:
#   kitname:
#     delay: 3600 (delay in seconds)
#     items:
#       - itemid amount

kits:
  tools:
    delay: 3600
    items:
      - stone_pickaxe 1
      - stone_axe 1
      - stone_shovel 1
      - stone_hoe 1
      - bread 16

############################################################
# +------------------------------------------------------+ #
# |                   EssentialsX Spawn                  | #
# +------------------------------------------------------+ #
############################################################

# This section controls the spawn-related functions of EssentialsX.

# When we spawn for the first time, which spawnpoint do we use?
# Set to "default" to use the server default spawnpoint.
# Set to "none" if you want to disable spawning.
spawnpoint: default

# Do we want to teleport the player to their home on join?
# If set to true, the player will teleport to their home on join.
# If set to false, the player will teleport to spawn on join.
teleport-to-home-on-join: false

# What priority should we use for handling respawn events?
# Set to 'none' to disable respawn handling.
# Set to 'low', 'normal', 'high', or 'highest' to enable respawn handling.
respawn-listener-priority: high

# What priority should we use for handling join events?
# Set to 'none' to disable join handling.
# Set to 'low', 'normal', 'high', or 'highest' to enable join handling.
join-listener-priority: high
`;
}

function generateLuckPermsConfig(config: ServerConfig): string {
  return `# LuckPerms Configuration
# Generated by StartServer
# 
# Server: ${config.serverName}
# Generated: ${new Date().toISOString()}

name: ${config.serverName}-luckperms
storage-method: h2

# Data storage settings
data:
  # Database settings (if using MySQL/PostgreSQL)
  address: localhost
  database: minecraft
  username: root
  password: ''
  
  # H2/MongoDB settings
  file: luckperms-h2

# Server name (for BungeeCord/Velocity networks)
server: ${config.serverName}

# Sync settings
sync-minutes: -1

# Watch config files for changes
watch-files: true

# Enable temporary permissions
temporary-add-behaviour: accept

# Primary group calculation
primary-group-calculation: stored

# Argument based command permissions
argument-based-command-permissions: false

# Require the player to be online for certain commands
require-online: false

# Disable certain commands
disable-ops: false

# Enable verbose logging
verbose: false
`;
}

function generateGriefPreventionConfig(config: ServerConfig): string {
  return `# GriefPrevention Configuration
# Generated by StartServer
#
# Server: ${config.serverName}
# Generated: ${new Date().toISOString()}

GriefPrevention:
  # The number of claim blocks given to new players
  InitialClaimBlocks: 100
  
  # The number of claim blocks earned per hour of play
  BlocksAccruedPerHour: 100
  
  # The maximum number of claim blocks a player can have
  MaxAccruedClaimBlocks: 80000
  
  # Whether to allow players to resize their claims
  AllowResizingClaims: true
  
  # Minimum claim size (width and height)
  MinClaimSize: 10
  
  # Whether to protect claims from TNT explosions
  Claims:
    PreventTntExplosion: true
    PreventFireSpreading: true
    
  # PvP settings
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    
  # Economy settings (requires Vault)
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
`;
}

function generateTABConfig(config: ServerConfig): string {
  return `# TAB Configuration
# Generated by StartServer
#
# Server: ${config.serverName}
# Generated: ${new Date().toISOString()}

# Header and footer for all players
header-footer:
  enabled: true
  header:
    - '&6&l${config.serverName}'
    - '&7Online: &f%online%&7/&f${config.maxPlayers}'
    - ''
  footer:
    - ''
    - '&7Ping: &f%ping%ms'
    - '&7TPS: &f%tps%'

# Player list customization
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: true
  character-width-overrides: {}
  
# Tab list groups
groups:
  Owner:
    tabprefix: '&4[Owner] &4'
    tabsuffix: ''
  Admin:
    tabprefix: '&c[Admin] &c'
    tabsuffix: ''
  Moderator:
    tabprefix: '&9[Mod] &9'
    tabsuffix: ''
  Player:
    tabprefix: '&7'
    tabsuffix: ''

# Scoreboard configuration
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  
  # Default scoreboard
  default-scoreboard:
    title: '&6&l${config.serverName}'
    lines:
      - '&7&m----------------'
      - '&6Name: &f%player%'
      - '&6Rank: &f%group%'
      - ''
      - '&6Online: &f%online%&7/&f${config.maxPlayers}'
      - '&7&m----------------'

# Placeholder settings
placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "HH:mm:ss"
  time-offset: 0
`;
}

function generateCoreProtectConfig(config: ServerConfig): string {
  return `# CoreProtect Configuration
# Generated by StartServer
#
# Server: ${config.serverName}
# Generated: ${new Date().toISOString()}

# CoreProtect configuration
# For help, visit: https://docs.coreprotect.net/

# MySQL configuration (if using MySQL)
mysql:
  host: localhost
  port: 3306
  database: coreprotect
  username: root
  password: ''
  prefix: co_
  ssl: false

# SQLite configuration
sqlite:
  database: database.db

# Logging settings
logging:
  block-place: true
  block-break: true
  natural-break: false
  block-movement: true
  pistons: true
  block-burn: true
  block-ignite: true
  explosions: true
  sign-text: true
  buckets: true
  leaves-decay: true
  tree-growth: true
  mushroom-growth: true
  vine-growth: true
  sculk-spread: true
  portals: true
  water-flow: true
  lava-flow: true
  liquid-tracking: false

# Player logging
player-logging:
  player-commands: true
  player-chat: true
  player-joins: true
  player-quits: true
  player-deaths: true
  player-drops: true
  player-pickups: true
  teleports: true

# Rollback settings
rollback:
  max-radius: 100
  default-radius: 10
  max-time: 0

# Lookup settings
lookup:
  max-rows: 1000
  default-rows: 100

# Purge settings
purge:
  enabled: false
  days: 30
  interval: 12
`;
}

function generateDiscordSRVConfig(config: ServerConfig): string {
  return `# DiscordSRV Configuration
# Generated by StartServer
#
# Server: ${config.serverName}
# Generated: ${new Date().toISOString()}

# Discord bot token (REQUIRED - get from https://discord.com/developers/applications)
BotToken: "YOUR_BOT_TOKEN_HERE"

# Discord channels
Channels:
  # Channel for server chat (channel ID)
  global: "000000000000000000"

# Minecraft to Discord settings
MinecraftDiscordAccountLinked:
  # Enable linked accounts feature
  Enabled: false

# Game status
DiscordGameStatus:
  - "Minecraft Server"
  - "${config.serverName}"

# Minecraft to Discord messages
MinecraftChatToDiscordMessageFormat: "**%displayname%**: %message%"
DiscordToMinecraftChatMessageFormat: "&b[Discord] &f%name%: %message%"

# Join/leave messages
MinecraftPlayerJoinMessage:
  Enabled: true
  Message: "%displayname% joined the server"

MinecraftPlayerLeaveMessage:
  Enabled: true
  Message: "%displayname% left the server"

# Death messages
MinecraftPlayerDeathMessage:
  Enabled: true
  Message: "%deathmessage%"

# Achievement/advancement messages
MinecraftPlayerAchievementMessages:
  Enabled: true
  Message: "%displayname% has made the advancement **%achievement%**"

# Console channel (optional)
DiscordConsoleChannelId: "000000000000000000"
DiscordConsoleChannelUsageLog: "Console-%date%.log"

# Server watchdog
ServerWatchdogMessage: "Server has crashed!"
ServerWatchdogEnabled: true
`;
}
