import type { ServerConfig } from '../types.js';

export function generateStartScript(config: ServerConfig): { sh: string; bat: string } {
  const jarName = getJarName(config.engine, config.version);
  const ramFlag = `-Xms${config.ramGb}G -Xmx${config.ramGb}G`;
  
  // Linux/Mac optimized flags (useTransparentHugePages works on Linux)
  const linuxFlags = '-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+UseStringDeduplication -XX:+UseLargePages -XX:+UseTransparentHugePages';
  
  // Windows compatible flags (no Linux-specific options)
  const windowsFlags = '-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+UseStringDeduplication';
  
  // Bash script (Linux/Mac)
  const sh = `#!/bin/bash
# Minecraft Server Start Script
# Generated by StartServer

cd "$(dirname "$0")"

# Check if Java is installed
if ! command -v java &> /dev/null; then
    echo "Java is not installed or not in PATH"
    echo "Please install Java 17 or newer"
    exit 1
fi

echo "Starting Minecraft ${config.engine} server version ${config.version}..."
echo "Allocated RAM: ${config.ramGb}GB"

java ${ramFlag} ${linuxFlags} -jar "${jarName}" --nogui
`;

  // Batch script (Windows)
  const bat = `@echo off
REM Minecraft Server Start Script
REM Generated by StartServer

cd /d "%~dp0"

REM Check if Java is installed
java -version >nul 2>&1
if errorlevel 1 (
    echo Java is not installed or not in PATH
    echo Please install Java 17 or newer
    pause
    exit /b 1
)

echo Starting Minecraft ${config.engine} server version ${config.version}...
echo Allocated RAM: ${config.ramGb}GB

java ${ramFlag} ${windowsFlags} -jar "${jarName}" --nogui
pause
`;

  return { sh, bat };
}

function getJarName(engine: string, version: string): string {
  switch (engine.toLowerCase()) {
    case 'vanilla':
      return 'server.jar';
    case 'paper':
      return `paper-${version}.jar`;
    case 'folia':
      return `folia-${version}.jar`;
    case 'purpur':
      return `purpur-${version}.jar`;
    case 'fabric':
      return `fabric-server-${version}.jar`;
    case 'forge':
      // Forge uses a specific naming convention
      return `forge-${version}-*.jar`;
    case 'neoforge':
      return 'neoforge-*.jar';
    case 'spigot':
      return `spigot-${version}.jar`;
    default:
      return 'server.jar';
  }
}
